name: Continuous Integration

on:
  pull_request:
  push:

jobs:
  build:
    name: Build and Test
    strategy:
      matrix:
        os: [ubuntu-latest]
        java: [17]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout current branch (full)
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Java and Scala
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
      - name: Cache sbt
        uses: coursier/cache-action@v6
      - name: Build project
        run: sbt test
